# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

##########################################################################################
# Be sure to edit the values below
##########################################################################################

title: U.S. Committee on the <br>Marine Transportation System
email: info@cmts.gov
description: >- # this means to ignore newlines until "baseurl:"
  The CMTS serves as a Federal interagency coordinating committee for the purpose of assessing the adequacy of the marine transportation system, promoting the integration of the marine transportation system with other modes of transportation and other uses of the marine environment, and coordinating, improving the coordination of, and making recommendations with regard to Federal policies that impact the marine transportation system.

baseurl: ""
#baseurl: "/webapplications/a072_cmts/cmts" # the subpath of your site, e.g. /blog

#url: trobins15.github.io

# url: "https://example.gov" # the base hostname & protocol for your site, e.g. https://example.com.
  # Required to support the jekyll-sitemap plugin below.
  # Uncomment the url line when ready to push to production. If using different branches for multiple
  # custom domains, edit this url parameter in the relevant branch to match the relevant custom domain.

# Twitter handle. Only the handle, not the URL.
twitter: uscmts

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
  # agency: your-agency

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: "Home"
    url: /
  - name: "Why the CMTS Matters"
    children:
      - name: "Why the CMTS Matters"
        url: "/why-cmts-matters/"
      - name: "National Strategy for the MTS"
        url: "/national-strategy/"
      - name: "MTS Priorities and CMTS Recommendations"
        url: "/priorities/"
  - name: "About CMTS"
    children:
      - name: "What We Do"
        url: "/about-us/"
      - name: "Organizational Structure"
        url: "/organizational-structure/"
      - name: "Background - Why the CMTS Matters"
        url: "/why-cmts-matters/"
      - name: "Background - History"
        url: "/history/"
      - name: "Background - Directives"
        url: "/directives/"        
  - name: "Topics/Projects"
    children:
      - name: "Artic Transportation"
        url: "/arctic/"
      - name: "COVID"
        url: "/covid/"
      - name: "Energy and Air Emissions"
        url: "/energy/"
      - name: "Environmental Stewardship"
        url: "/environmental/"
      - name: "Future of Navigation"
        url: "/future/"
      - name: "Infrastructure Investment"
        url: "/infrastructure/"
      - name: "Maritime Data"
        url: "/maritime/"
      - name: "Military to Mariner"
        url: "/military/"
      - name: "Ocean Policy"
        url: "/ocean-policy/"
      - name: "Research and Development"
        url: "/research/"
      - name: "MTS Resilience"
        url: "/resilience/"
      #- name: "Speaker Series"
      #  url: "/speaker/"     
  - name: "Resources"
    children:
      - name: "Compendium"
        url: "/compendium/"
      - name: "Downloads"
        url: "/downloads/"
  - name: "News and Events"
    children:
      - name: "Events"
        url: "/events/"
      - name: "IAT Activity"
        url: "/iat-activity/"
      - name: "Information Update"
        url: "/information-update/"   
      - name: "Messages From Leadership"
        url: "/leadership-messages/"
      - name: "Organizational Change"
        url: "/organizational-change/"
      - name: "Press Release"
        url: "/press-release/"
      - name: "Policy Change"
        url: "/policy-change/"
      - name: "Resource Update"
        url: "/resource-update/"
      - name: "Technology Update"
        url: "/technology-update/"
    #url: /document-with-sidenav/
    
#secondary_navigation:
#  - name: Search Documents
#    url: "https://search.usa.gov/search?affiliate=cmts&dc=9316"
#  - name: Another secondary link
#    url: "#main-content"

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: cmts

  # Replace this with your access key.
  access_key: V5W7zi9WBVxI9ee--1X1L90deBsHCC94s1VmIjqWWvw=

  # This renders the results within the page instead of sending to user to search.gov.
  inline: true

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box. 
  # If you do not want to present search suggestions, set this value to false.
  suggestions: true

  #bypass api and go to search.usa.gov bing webpage and documents collection
  endpoint_bingsearch: https://search.usa.gov/search/docs

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################

collections:
  pages:
    output: true
    permalink: /:path/
    
  docposts:
    output: true
    permalink: /:path/

permalink: pretty

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-sitemap # See additional instructions for url parameter above.
  - jekyll-seo-tag

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: "posts"
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 3
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page/:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.
  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ":title - page :num"
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: "date"
  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: "posts"
  # Optional, the default tag to use, omit to disable
  tag: ""
  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts,
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: ""
  # Optional,omit or set both before and after to zero to disable.
  # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html
  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: "index.html"


#incremental: true

exclude:
  - package.json
  - package-lock.json
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md
  - degit.json
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - Dockerfile

assets:
  sources:
    - node_modules/uswds/dist/img
    - node_modules/uswds/dist/js
    - node_modules/uswds/dist/scss
    - node_modules/netlify-cms/dist

